{% set name = "puma" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nasa/puma/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 23b82de2005d1f046ef7b4857491e9364d92802c965c18b00f0e98f0b5aafc82

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cmake >=3.11.0
    - make
    - swig
  host:
    - xorg-libxfixes  # [linux]
    - python
    - pip
    - setuptools
    - numpy
    - eigen
    - fftw
    - libtiff
    - qt
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-image
    # because of bug in scikit, we need this dependency
    # might be able to remove it in the future
    - pooch <=1.4.0
    - matplotlib-base
    - pyevtk
    - fenics-dolfin
    - pyvista

test:
  imports:
    - TexGen.Core
    - pumapy
  source_files:
    - python/test/*.py

about:
  home: https://github.com/nasa/puma
  license: NASA-1.3
  license_file:
    - LICENSE.txt
    - install/TexGen/LICENSE.txt
    - gui/src/Utilities/qcustomplot/GPL.txt
  summary: A package to compute material properties from micro-CT data.
  description: |
    The Porous Microstructure Analysis (PuMA) software has been developed in order to 
    compute effective material properties and perform material response simulations on 
    digitized microstructures of porous media. PuMA is able to import digital three-dimensional 
    images obtained from X-ray microtomography or to generate artificial microstructures 
    that mimic real materials. PuMA also provides a module for interactive 3D visualizations. 
    Version 3 includes modules to compute simple morphological properties such as porosity, 
    volume fractions, pore diameter, and specific surface area. Additional capabilities include 
    the determination of effective thermal and electrical conductivity (including the ability 
    to simulate local anisotropy), effective diffusivity and tortuosity from the continuum to 
    the rarefied regime, and techniques to determine local material orientation.
  doc_url: https://puma-nasa.readthedocs.io/
  dev_url: https://gitlab.com/jcfergus/puma-dev

extra:
  recipe-maintainers:
    - fsemerar
